packages:
  - 'packages/*'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/cordis@4.0.5-alpha.1'
  - '@deepseek-ai/dsh-host-webserver@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-connection@0.2.1-alpha.1'
